"""empty message

Revision ID: 02bcf25a525e
Revises: 9316018850d9
Create Date: 2021-05-17 23:51:03.328454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bcf25a525e'
down_revision = '9316018850d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('item_total_rating',
    # sa.Column('item_id', sa.Integer(), nullable=False),
    # sa.Column('total_rating', sa.Integer(), nullable=True),
    # sa.Column('num_customer', sa.Integer(), nullable=True),
    # sa.Column('coefficient', sa.Numeric(precision=15, scale=10), nullable=True),
    # sa.PrimaryKeyConstraint('item_id')
    # )
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_table('item_total_rating')
    # ### end Alembic commands ###
