"""initial migration

Revision ID: 15ec0f642daa
Revises: 
Create Date: 2022-03-03 02:51:40.147463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ec0f642daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #category table
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    
    #customer table
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.LargeBinary(), nullable=False),
    sa.Column('last_name', sa.LargeBinary(), nullable=False),
    sa.Column('gender', sa.LargeBinary(), nullable=False),
    sa.Column('telephone', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.LargeBinary(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('street', sa.LargeBinary(), nullable=True),
    sa.Column('town', sa.LargeBinary(), nullable=False),
    sa.Column('parish', sa.LargeBinary(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    
    #employee table
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.LargeBinary(), nullable=False),
    sa.Column('last_name', sa.LargeBinary(), nullable=False),
    sa.Column('telephone', sa.LargeBinary(), nullable=True),
    sa.Column('email', sa.LargeBinary(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('street', sa.LargeBinary(), nullable=False),
    sa.Column('town', sa.LargeBinary(), nullable=False),
    sa.Column('parish', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.LargeBinary(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    
    #parish table
    op.create_table('parish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.LargeBinary(), nullable=True),
    sa.Column('shipping_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    #product table
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grams_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'size', name='_product_name_size_uc'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    
    #tax table
    op.create_table('tax',
    sa.Column('tax', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('tax')
    )
    
    #cart table
    op.create_table('cart',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'product_id')
    )
    op.create_index(op.f('ix_cart_customer_id'), 'cart', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cart_product_id'), 'cart', ['product_id'], unique=False)
    
    #orders table
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderdate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.LargeBinary(), nullable=False),
    sa.Column('payment_type', sa.LargeBinary(), nullable=False),
    sa.Column('billing_first_name', sa.LargeBinary(), nullable=False),
    sa.Column('billing_last_name', sa.LargeBinary(), nullable=False),
    sa.Column('billing_street', sa.LargeBinary(), nullable=False),
    sa.Column('billing_town', sa.LargeBinary(), nullable=False),
    sa.Column('billing_parish', sa.LargeBinary(), nullable=False),
    sa.Column('shipping_first_name', sa.LargeBinary(), nullable=False),
    sa.Column('shipping_last_name', sa.LargeBinary(), nullable=False),
    sa.Column('shipping_timeslot_start', sa.Time(), nullable=False),
    sa.Column('shipping_timeslot_end', sa.Time(), nullable=False),
    sa.Column('shipping_date', sa.Date(), nullable=False),
    sa.Column('shipping_street', sa.LargeBinary(), nullable=False),
    sa.Column('shipping_town', sa.LargeBinary(), nullable=False),
    sa.Column('shipping_parish', sa.LargeBinary(), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivered_time', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('checkout_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['checkout_by'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    
    #product_category table
    op.create_table('product_category',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_index(op.f('ix_product_category_category_id'), 'product_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_category_product_id'), 'product_category', ['product_id'], unique=False)
    
    
    #product rating table
    op.create_table('product_rating',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'product_id')
    )
    
    #shipping_time_slot table
    op.create_table('shipping_time_slot',
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_per_slot', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parish_id'),
    sa.UniqueConstraint('parish_id', 'day', 'start_time', 'end_time', name='_shipping_time_slot_parish_id_day_start_time_end_time_uc')
    )
    op.create_index(op.f('ix_shipping_time_slot_parish_id'), 'shipping_time_slot', ['parish_id'], unique=False)
    

    #order_item table
    op.create_table('order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    
    #payment table
    op.create_table('payment',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('amount_tendered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('intent_id', sa.LargeBinary(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('intent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_shipping_time_slot_parish_id'), table_name='shipping_time_slot')
    op.drop_table('shipping_time_slot')
    op.drop_table('product_rating')
    op.drop_index(op.f('ix_product_category_product_id'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_category_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cart_product_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_customer_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_table('tax')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('parish')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
