"""empty message

Revision ID: 1addc3d20363
Revises: 73c073c4093c
Create Date: 2021-05-08 12:53:48.916812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1addc3d20363'
down_revision = '73c073c4093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_item_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_cart_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'grocery', ['item_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'customer', ['cart_id'], ['id'])
    op.alter_column('grocery', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'grocery', ['sku'])
    op.drop_constraint('order_groceries_grocery_id_fkey', 'order_groceries', type_='foreignkey')
    op.drop_constraint('order_groceries_order_id_fkey', 'order_groceries', type_='foreignkey')
    op.create_foreign_key(None, 'order_groceries', 'grocery', ['grocery_id'], ['id'])
    op.create_foreign_key(None, 'order_groceries', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('orders_checkout_by_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_deliveryparish_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'delivery_parish', ['deliveryparish'], ['parish'])
    op.create_foreign_key(None, 'orders', 'employee', ['checkout_by'], ['id'])
    op.create_foreign_key(None, 'orders', 'customer', ['customer_id'], ['id'])
    op.drop_constraint('payment_recorded_by_fkey', 'payment', type_='foreignkey')
    op.drop_constraint('payment_order_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'employee', ['recorded_by'], ['id'])
    op.drop_constraint('rating_cust_id_fkey', 'rating', type_='foreignkey')
    op.drop_constraint('rating_item_id_fkey', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'customer', ['cust_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'grocery', ['item_id'], ['id'])
    op.drop_constraint('taxes_on_goods_grocery_id_fkey', 'taxes_on_goods', type_='foreignkey')
    op.drop_constraint('taxes_on_goods_tax_fkey', 'taxes_on_goods', type_='foreignkey')
    op.create_foreign_key(None, 'taxes_on_goods', 'grocery', ['grocery_id'], ['id'])
    op.create_foreign_key(None, 'taxes_on_goods', 'taxes', ['tax'], ['tax'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taxes_on_goods', type_='foreignkey')
    op.drop_constraint(None, 'taxes_on_goods', type_='foreignkey')
    op.create_foreign_key('taxes_on_goods_tax_fkey', 'taxes_on_goods', 'taxes', ['tax'], ['tax'], ondelete='CASCADE')
    op.create_foreign_key('taxes_on_goods_grocery_id_fkey', 'taxes_on_goods', 'grocery', ['grocery_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_item_id_fkey', 'rating', 'grocery', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('rating_cust_id_fkey', 'rating', 'customer', ['cust_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_order_id_fkey', 'payment', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payment_recorded_by_fkey', 'payment', 'employee', ['recorded_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_deliveryparish_fkey', 'orders', 'delivery_parish', ['deliveryparish'], ['parish'], ondelete='SET NULL')
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customer', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orders_checkout_by_fkey', 'orders', 'employee', ['checkout_by'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'order_groceries', type_='foreignkey')
    op.drop_constraint(None, 'order_groceries', type_='foreignkey')
    op.create_foreign_key('order_groceries_order_id_fkey', 'order_groceries', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_groceries_grocery_id_fkey', 'order_groceries', 'grocery', ['grocery_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'grocery', type_='unique')
    op.alter_column('grocery', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_cart_id_fkey', 'cart', 'customer', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_item_id_fkey', 'cart', 'grocery', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
