"""empty message

Revision ID: 2d14cbf595f1
Revises: 
Create Date: 2021-04-14 04:47:33.520822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d14cbf595f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'telephone', type_=sa.String(length=11))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'telephone', type_=sa.Integer())
    # ### end Alembic commands ###
