"""empty message

Revision ID: 3c35134e2bd8
Revises: 35581ac21d31
Create Date: 2021-05-25 23:38:09.867455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c35134e2bd8'
down_revision = '35581ac21d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miscellaneous', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('miscellaneous', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_column('miscellaneous', 'max_deliveries_per_time_slot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miscellaneous', sa.Column('max_deliveries_per_time_slot', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('miscellaneous', 'value')
    op.drop_column('miscellaneous', 'name')
    # ### end Alembic commands ###
