"""updated order_item table, changed name of product_rating table, change appropriate tables to include 'time_created' field

Revision ID: 4e52e9c66aa3
Revises: 4feb0fc114ca
Create Date: 2022-03-09 00:54:23.742289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e52e9c66aa3'
down_revision = '4feb0fc114ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_product_rating',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'product_id')
    )

    op.drop_table('product_rating')
    
    op.add_column('customer', sa.Column('time_created', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('is_active', sa.Boolean(), nullable=False))

    op.add_column('employee', sa.Column('time_created', sa.DateTime(), nullable=False))
    
    op.add_column('order_item', sa.Column('product_name', sa.String(length=100), nullable=True))
    op.add_column('order_item', sa.Column('product_sku', sa.String(length=50), nullable=True))
    op.add_column('order_item', sa.Column('product_grams_per_unit', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_item', sa.Column('product_brand', sa.String(length=100), nullable=True))
    op.add_column('order_item', sa.Column('product_package_type', sa.String(length=50), nullable=True))
    op.alter_column('order_item', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('order_item', 'sku')
    op.add_column('orders', sa.Column('time_created', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('billing_telephone', sa.LargeBinary(), nullable=False))
    op.add_column('orders', sa.Column('shipping_telephone', sa.LargeBinary(), nullable=False))
    op.drop_column('orders', 'order_time')
    op.add_column('payment', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('payment', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('type', sa.String(length=50), nullable=False))
    op.drop_column('payment', 'payment_time')
    op.add_column('product', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('product', sa.Column('time_created', sa.DateTime(), nullable=False))
    op.drop_column('product', 'category')
    op.drop_column('product', 'cost_per_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipping_time_slot_id'), table_name='shipping_time_slot')
    op.create_index('ix_shipping_time_slot_id', 'shipping_time_slot', ['id'], unique=False)
    op.add_column('product', sa.Column('cost_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('product', 'time_created')
    op.drop_column('product', 'unit_price')
    op.add_column('payment', sa.Column('payment_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('payment', 'type')
    op.drop_column('payment', 'time_created')
    op.drop_column('payment', 'id')
    op.add_column('orders', sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'shipping_telephone')
    op.drop_column('orders', 'billing_telephone')
    op.drop_column('orders', 'time_created')
    op.add_column('order_item', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('order_item', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('order_item', 'product_package_type')
    op.drop_column('order_item', 'product_brand')
    op.drop_column('order_item', 'product_grams_per_unit')
    op.drop_column('order_item', 'product_sku')
    op.drop_column('order_item', 'product_name')
    op.drop_column('employee', 'time_created')
    op.create_unique_constraint('customer_email_key', 'customer', ['email'])
    op.drop_column('customer', 'is_active')
    op.drop_column('customer', 'time_created')
    op.create_table('product_rating',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='product_rating_customer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_rating_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'product_id', name='product_rating_pkey')
    )
    op.drop_table('customer_product_rating')
    # ### end Alembic commands ###
