"""updated time slot tables and d order table

Revision ID: 4feb0fc114ca
Revises: 15ec0f642daa
Create Date: 2022-03-04 01:36:12.326033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4feb0fc114ca'
down_revision = '15ec0f642daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cart_item',
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('customer_id', 'product_id')
    )
    op.create_index(op.f('ix_cart_item_customer_id'), 'cart_item', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cart_item_product_id'), 'cart_item', ['product_id'], unique=False)
    
    
    op.create_table(
        'default_config_shipping_time_slot',
        sa.Column('parish_id', sa.Integer(), nullable=False),
        sa.Column('day', sa.Integer(), nullable=False),
        sa.Column('time_slot_interval', sa.Interval(), nullable=False),
        sa.Column('max_per_slot', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['parish_id'], ['parish.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('parish_id', 'day')
    )
    
    # delete cart table 
    op.drop_index('ix_cart_customer_id', table_name='cart')
    op.drop_index('ix_cart_product_id', table_name='cart')
    op.drop_table('cart')
    
    # op.drop_constraint('customer_email_key', 'customer', type_='unique')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    
    
    op.add_column('shipping_time_slot', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('shipping_time_slot', sa.Column('num_space_available', sa.Integer(), nullable=False))
    op.drop_constraint('_shipping_time_slot_parish_id_day_start_time_end_time_uc', 'shipping_time_slot', type_='unique')
    op.drop_index('ix_shipping_time_slot_parish_id', table_name='shipping_time_slot')
    op.create_index(op.f('ix_shipping_time_slot_id'), 'shipping_time_slot', ['id'], unique=True)
    op.create_unique_constraint('shipping_time_slot_parish_id_start_time_end_time_uc', 'shipping_time_slot', ['parish_id', 'start_time', 'end_time'])
    op.drop_column('shipping_time_slot', 'max_per_slot')
    op.drop_column('shipping_time_slot', 'day')



    # add new columns to order table
    op.add_column('orders', sa.Column('order_time', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('shipping_time_slot_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'shipping_time_slot', ['shipping_time_slot_id'], ['id'], ondelete='SET NULL')
    
    #drop columns from orders table
    op.drop_column('orders', 'shipping_timeslot_start')
    op.drop_column('orders', 'shipping_date')
    op.drop_column('orders', 'shipping_timeslot_end')
    op.drop_column('orders', 'orderdate')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_time_slot', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shipping_time_slot', sa.Column('max_per_slot', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('shipping_time_slot_parish_id_start_time_end_time_uc', 'shipping_time_slot', type_='unique')
    op.drop_index(op.f('ix_shipping_time_slot_id'), table_name='shipping_time_slot')
    op.create_index('ix_shipping_time_slot_parish_id', 'shipping_time_slot', ['parish_id'], unique=False)
    op.create_unique_constraint('_shipping_time_slot_parish_id_day_start_time_end_time_uc', 'shipping_time_slot', ['parish_id', 'day', 'start_time', 'end_time'])
    op.drop_column('shipping_time_slot', 'num_space_available')
    op.drop_column('shipping_time_slot', 'id')
    op.add_column('orders', sa.Column('orderdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_timeslot_end', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_timeslot_start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_time_slot')
    op.drop_column('orders', 'order_time')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_unique_constraint('customer_email_key', 'customer', ['email'])
    op.create_table('cart',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='cart_customer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='cart_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'product_id', name='cart_pkey')
    )
    op.create_index('ix_cart_product_id', 'cart', ['product_id'], unique=False)
    op.create_index('ix_cart_customer_id', 'cart', ['customer_id'], unique=False)
    op.drop_table('default_config_shipping_time_slot')
    op.drop_index(op.f('ix_cart_item_product_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_customer_id'), table_name='cart_item')
    op.drop_table('cart_item')
    # ### end Alembic commands ###
