"""empty message

Revision ID: 59dccd722ede
Revises: 
Create Date: 2021-03-02 11:04:29.480417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59dccd722ede'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
