"""empty message

Revision ID: 73c073c4093c
Revises: 7f7778beb395
Create Date: 2021-05-07 23:37:24.390301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c073c4093c'
down_revision = '7f7778beb395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery', sa.Column('sku', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery', 'sku')
    # ### end Alembic commands ###
