"""empty message

Revision ID: 7f7778beb395
Revises: a2a8506228b6
Create Date: 2021-04-27 23:03:25.861907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7778beb395'
down_revision = 'a2a8506228b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery', sa.Column('photo', sa.String(length=100), nullable=True))
    op.alter_column('grocery', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Meat'::character varying"))
    op.create_foreign_key(None, 'orders', 'delivery_parish', ['deliveryparish'], ['parish'])
    op.drop_constraint('taxes_on_goods_grocery_id_fkey', 'taxes_on_goods', type_='foreignkey')
    op.drop_constraint('taxes_on_goods_tax_fkey', 'taxes_on_goods', type_='foreignkey')
    op.create_foreign_key(None, 'taxes_on_goods', 'grocery', ['grocery_id'], ['id'])
    op.create_foreign_key(None, 'taxes_on_goods', 'taxes', ['tax'], ['tax'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taxes_on_goods', type_='foreignkey')
    op.drop_constraint(None, 'taxes_on_goods', type_='foreignkey')
    op.create_foreign_key('taxes_on_goods_tax_fkey', 'taxes_on_goods', 'taxes', ['tax'], ['tax'], ondelete='CASCADE')
    op.create_foreign_key('taxes_on_goods_grocery_id_fkey', 'taxes_on_goods', 'grocery', ['grocery_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('grocery', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Meat'::character varying"))
    op.drop_column('grocery', 'photo')
    # ### end Alembic commands ###
