"""empty message

Revision ID: 8c977471798e
Revises: 67adc76e0b5f
Create Date: 2021-05-15 13:23:48.811699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c977471798e'
down_revision = '67adc76e0b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_payment',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('amount_tendered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('intent_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('intent_id')
    )
    op.create_table('cash_payment',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('amount_tendered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('payment')
    op.add_column('customer', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.add_column('customer', sa.Column('street', sa.String(length=45), nullable=True))
    op.alter_column('delivery_time_slot', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_time_slot', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('customer', 'street')
    op.drop_column('customer', 'email_confirmed')
    op.create_table('payment',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('amount_tendered', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('change', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payment_order_id_fkey'),
    sa.ForeignKeyConstraint(['recorded_by'], ['employee.id'], name='payment_recorded_by_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='payment_pkey')
    )
    op.drop_table('cash_payment')
    op.drop_table('card_payment')
    # ### end Alembic commands ###
