"""empty message

Revision ID: 8dd4e24692b9
Revises: 
Create Date: 2021-04-14 02:18:13.647432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dd4e24692b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_item_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_cart_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'customer', ['cart_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'grocery', ['item_id'], ['id'])
    op.drop_constraint('order_groceries_order_id_fkey', 'order_groceries', type_='foreignkey')
    op.drop_constraint('order_groceries_grocery_id_fkey', 'order_groceries', type_='foreignkey')
    op.create_foreign_key(None, 'order_groceries', 'grocery', ['grocery_id'], ['id'])
    op.create_foreign_key(None, 'order_groceries', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'deliverydate', new_column_name='deliveryDate', existing_type=sa.DateTime(),nullable=True)
    op.alter_column('orders', 'deliveryparish',new_column_name='deliveryParish', existing_type=sa.String(length=45), nullable=True)
    op.alter_column('orders', 'deliverytown', new_column_name='deliveryTown',existing_type=sa.String(length=45), nullable=True)
    op.alter_column('orders', 'orderdate', new_column_name='orderDate',existing_type=sa.DateTime(), nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('orders_checkout_by_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'employee', ['checkout_by'], ['id'])
    op.create_foreign_key(None, 'orders', 'customer', ['customer_id'], ['id'])
    op.drop_constraint('payment_recorded_by_fkey', 'payment', type_='foreignkey')
    op.drop_constraint('payment_order_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'employee', ['recorded_by'], ['id'])
    op.drop_constraint('rating_cust_id_fkey', 'rating', type_='foreignkey')
    op.drop_constraint('rating_item_id_fkey', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'grocery', ['item_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'customer', ['cust_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_item_id_fkey', 'rating', 'grocery', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('rating_cust_id_fkey', 'rating', 'customer', ['cust_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_order_id_fkey', 'payment', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payment_recorded_by_fkey', 'payment', 'employee', ['recorded_by'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('orderdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('deliverydate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('deliveryparish', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('deliverytown', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customer', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orders_checkout_by_fkey', 'orders', 'employee', ['checkout_by'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'orderDate')
    op.drop_column('orders', 'deliveryTown')
    op.drop_column('orders', 'deliveryParish')
    op.drop_column('orders', 'deliveryDate')
    op.drop_constraint(None, 'order_groceries', type_='foreignkey')
    op.drop_constraint(None, 'order_groceries', type_='foreignkey')
    op.create_foreign_key('order_groceries_grocery_id_fkey', 'order_groceries', 'grocery', ['grocery_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_groceries_order_id_fkey', 'order_groceries', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_cart_id_fkey', 'cart', 'customer', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_item_id_fkey', 'cart', 'grocery', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
