"""empty message

Revision ID: 9316018850d9
Revises: 8c977471798e
Create Date: 2021-05-17 22:04:35.858914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9316018850d9'
down_revision = '8c977471798e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('item_total_rating',
    # sa.Column('item_id', sa.Integer(), nullable=False),
    # sa.Column('total_rating', sa.Integer(), nullable=True),
    # sa.Column('num_customer', sa.Integer(), nullable=True),
    # sa.Column('coefficient', sa.Numeric(precision=15, scale=10), nullable=True),
    # sa.PrimaryKeyConstraint('item_id')
    # )
    op.add_column('orders', sa.Column('payment_type', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_type')
    op.drop_table('item_total_rating')
    # ### end Alembic commands ###
