"""empty message

Revision ID: a2a8506228b6
Revises: 2d14cbf595f1
Create Date: 2021-04-23 10:45:34.683207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2a8506228b6'
down_revision = '2d14cbf595f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_parish',
    sa.Column('parish', sa.String(length=45), nullable=False),
    sa.Column('delivery_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('parish')
    )
    op.create_table('taxes',
    sa.Column('tax', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('tax')
    )
    op.create_table('taxes_on_goods',
    sa.Column('tax', sa.String(), nullable=False),
    sa.Column('grocery_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_id'], ['grocery.id'], ),
    sa.ForeignKeyConstraint(['tax'], ['taxes.tax'], ),
    sa.PrimaryKeyConstraint('tax', 'grocery_id')
    )
    op.add_column('grocery', sa.Column('grams_per_unit', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('deliverydate', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('deliveryparish', sa.String(length=45), nullable=True))
    op.add_column('orders', sa.Column('deliverytown', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'orders', 'delivery_parish', ['deliveryparish'], ['parish'])
    op.drop_column('orders', 'deliveryparish')
    op.drop_column('orders', 'deliverydate')
    op.drop_column('orders', 'deliverytown')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deliverytown', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('deliverydate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('deliveryparish', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'deliveryTown')
    op.drop_column('orders', 'deliveryParish')
    op.drop_column('orders', 'deliveryDate')
    op.drop_column('grocery', 'grams_per_unit')
    op.drop_table('taxes_on_goods')
    op.drop_table('taxes')
    op.drop_table('delivery_parish')
    # ### end Alembic commands ###
