"""empty message

Revision ID: a34bab00d1ef
Revises: b7c21032df08
Create Date: 2021-05-26 05:24:27.758552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34bab00d1ef'
down_revision = 'b7c21032df08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_groceries_sku_key', 'order_groceries', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_groceries_sku_key', 'order_groceries', ['sku'])
    # ### end Alembic commands ###
