"""empty message

Revision ID: b7c21032df08
Revises: 44bf4d541cc0
Create Date: 2021-05-26 04:22:50.845579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7c21032df08'
down_revision = '44bf4d541cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'billing_parish')
    op.add_column('orders', sa.Column('billing_parish', sa.LargeBinary(), nullable=False))
    op.drop_column('orders', 'delivery_parish')
    op.add_column('orders', sa.Column('delivery_parish', sa.LargeBinary(), nullable=False))
    op.alter_column('orders', 'status',
            existing_type=postgresql.BYTEA(),
            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_column('orders', 'delivery_parish')
    op.add_column('orders', sa.Column('delivery_parish', sa.Integer(), nullable=False)) 
    op.drop_column('orders', 'billing_parish')
    op.add_column('orders', sa.Column('billing_parish', sa.Integer(), nullable=False))           
    # ### end Alembic commands ###
