"""empty message

Revision ID: d8588976ee39
Revises: 65b2138d78e0
Create Date: 2021-05-10 20:03:10.989947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8588976ee39'
down_revision = '65b2138d78e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_index(op.f('ix_grocery_id'), 'grocery', ['id'], unique=False)
    op.create_index(op.f('ix_order_groceries_order_id'), 'order_groceries', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_order_groceries_order_id'), table_name='order_groceries')
    op.drop_index(op.f('ix_grocery_id'), table_name='grocery')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    # ### end Alembic commands ###
