"""empty message

Revision ID: e839960818a7
Revises: e931ba415cc4
Create Date: 2021-05-19 17:52:34.859438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e839960818a7'
down_revision = 'e931ba415cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.LargeBinary(), nullable=False),
    sa.Column('last_name', sa.LargeBinary(), nullable=False),
    sa.Column('telephone', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.LargeBinary(), nullable=False),
    sa.Column('gender', sa.LargeBinary(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('street', sa.LargeBinary(), nullable=True),
    sa.Column('town', sa.LargeBinary(), nullable=False),
    sa.Column('parish', sa.LargeBinary(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.LargeBinary(), nullable=False),
    sa.Column('last_name', sa.LargeBinary(), nullable=False),
    sa.Column('telephone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.LargeBinary(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('street', sa.LargeBinary(), nullable=False),
    sa.Column('town', sa.LargeBinary(), nullable=False),
    sa.Column('parish', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.LargeBinary(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # op.create_table('item_total_rating',
    # sa.Column('item_id', sa.Integer(), nullable=False),
    # sa.Column('total_rating', sa.Integer(), nullable=True),
    # sa.Column('num_customer', sa.Integer(), nullable=True),
    # sa.Column('coefficient', sa.Numeric(precision=15, scale=10), nullable=True),
    # sa.PrimaryKeyConstraint('item_id')
    # )
    # op.create_table('count_pairs',
    # sa.Column('item1', sa.Integer(), nullable=False),
    # sa.Column('item2', sa.Integer(), nullable=False),
    # sa.Column('count', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['item1'], ['grocery.id'], ),
    # sa.ForeignKeyConstraint(['item2'], ['grocery.id'], ),
    # sa.PrimaryKeyConstraint('item1', 'item2')
    # )
    # op.create_table('total_amount_purchased',
    # sa.Column('cust_id', sa.Integer(), nullable=False),
    # sa.Column('grocery_id', sa.Integer(), nullable=False),
    # sa.Column('total', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ),
    # sa.ForeignKeyConstraint(['grocery_id'], ['grocery.id'], ),
    # sa.PrimaryKeyConstraint('cust_id', 'grocery_id')
    # )
    # op.create_table('total_quantity_purchased',
    # sa.Column('grocery_id', sa.Integer(), nullable=False),
    # sa.Column('total', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['grocery_id'], ['grocery.id'], ),
    # sa.PrimaryKeyConstraint('grocery_id')
    # )
    op.create_index(op.f('ix_cart_item_id'), 'cart', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_groceries_grocery_id'), 'order_groceries', ['grocery_id'], unique=False)
    op.create_index(op.f('ix_order_groceries_order_id'), 'order_groceries', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_groceries_order_id'), table_name='order_groceries')
    op.drop_index(op.f('ix_order_groceries_grocery_id'), table_name='order_groceries')
    op.drop_index(op.f('ix_cart_item_id'), table_name='cart')
    # op.drop_table('total_quantity_purchased')
    # op.drop_table('total_amount_purchased')
    # op.drop_table('count_pairs')
    # op.drop_table('item_total_rating')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
