"""empty message

Revision ID: e931ba415cc4
Revises: 02bcf25a525e
Create Date: 2021-05-18 10:19:46.551129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e931ba415cc4'
down_revision = '02bcf25a525e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('item_total_rating',
    # sa.Column('item_id', sa.Integer(), nullable=False),
    # sa.Column('total_rating', sa.Integer(), nullable=True),
    # sa.Column('num_customer', sa.Integer(), nullable=True),
    # sa.Column('coefficient', sa.Numeric(precision=15, scale=10), nullable=True),
    # sa.PrimaryKeyConstraint('item_id')
    # )
    # op.create_table('count_pairs',
    # sa.Column('item1', sa.Integer(), nullable=False),
    # sa.Column('item2', sa.Integer(), nullable=False),
    # sa.Column('count', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['item1'], ['grocery.id'], ),
    # sa.ForeignKeyConstraint(['item2'], ['grocery.id'], ),
    # sa.PrimaryKeyConstraint('item1', 'item2')
    # )
    # op.create_table('total_amount_purchased',
    # sa.Column('cust_id', sa.Integer(), nullable=False),
    # sa.Column('grocery_id', sa.Integer(), nullable=False),
    # sa.Column('total', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ),
    # sa.ForeignKeyConstraint(['grocery_id'], ['grocery.id'], ),
    # sa.PrimaryKeyConstraint('cust_id', 'grocery_id')
    # )
    # op.create_table('total_quantity_purchased',
    # sa.Column('grocery_id', sa.Integer(), nullable=False),
    # sa.Column('total', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['grocery_id'], ['grocery.id'], ),
    # sa.PrimaryKeyConstraint('grocery_id')
    # )
    op.add_column('employee', sa.Column('telephone', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('details', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'details')
    op.drop_column('employee', 'telephone')
    op.drop_table('total_quantity_purchased')
    op.drop_table('total_amount_purchased')
    op.drop_table('count_pairs')
    op.drop_table('item_total_rating')
    # ### end Alembic commands ###
