"""empty message

Revision ID: faffbff1c488
Revises: d8588976ee39
Create Date: 2021-05-10 20:09:25.950100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faffbff1c488'
down_revision = 'd8588976ee39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cart_cart_id'), 'cart', ['cart_id'], unique=False)
    op.drop_index('ix_order_groceries_order_id', table_name='order_groceries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_order_groceries_order_id', 'order_groceries', ['order_id'], unique=False)
    op.drop_index(op.f('ix_cart_cart_id'), table_name='cart')
    # ### end Alembic commands ###
